### ISSUE TITLE
Add roadmap to practice Data structures and Algorithms

### ISSUE THREAD

**Issue by justani** [mfaisalkhatri/awesome-learning#147]
I want to suggest this link which has learning content and practice problems on all the important data structures and algorithms.
Here is the link - https://www.codechef.com/roadmap/data-structures-and-algorithms

Please let me know if I need to make a PR to add it.

**Comment by mfaisalkhatri** [comment]
Plese add a PR

**Comment by mfaisalkhatri** [comment]
Please make sure you follow the guidenlines for merging in this repo

1. Raise an issue first for any update you need to make to this repo
2. Your commits needs to be signed and verified
3. The link you are adding should be updated under - Data Structures & Algorithms >> <Codechef link>
