### ISSUE TITLE
Add resources to learn BDD

### ISSUE THREAD

**Issue by mfaisalkhatri** [mfaisalkhatri/awesome-learning#38]

**Comment by GenerousDev** [comment]
Ceckout "Automation n Stuff by Bhadmus" by @bhadmusautomates on youtube.

**Comment by mfaisalkhatri** [comment]
1. Cucumber Installation - https://cucumber.io/docs/installation/
2. Cucumber Guides - https://cucumber.io/docs/guides/
3. Cucumber Documentation - https://cucumber.io/docs/cucumber/
4. Gherkin syntax - https://cucumber.io/docs/cucumber/
